using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEngine.AddressableAssets.ResourceLocators;
using UnityEngine.ResourceManagement.AsyncOperations;

namespace Ksp2UnityTools.Editor.Extensions
{
    public class LoadTkImportedCatalog : AssetPostprocessor
    {
        // This must be the same as the output of the ImportKsp2ToEditor pipeline.
        private const string loadTkImportedCatalogPath = "DoNotDistribute/aa/catalog.json";

        // Path must be relative to Assets directory.
        private const string reduxCatalogPath = "../Redux/Addressables/StandaloneWindows64/catalog.json";

#if TK_ADDRESSABLE
        /// <summary>
        /// Loads an addressable catalog into a resource locator after domain reload.
        /// This makes the path identifiers in the catalog accessible in the editor,
        /// even if the catalog isn't generated by this project's addressable build system.
        /// </summary>
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths,
            bool didDomainReload
        )
        {
            if (!didDomainReload)
            {
                return;
            }

            string tkAssetCatalogPath = loadTkImportedCatalogPath;
            string ksp2CatalogFullPath = Path.Join(Application.dataPath, tkAssetCatalogPath);

            if (!Addressables.ResourceLocators.Select(rl => rl.LocatorId).Contains(ksp2CatalogFullPath))
            {
                AsyncOperationHandle<IResourceLocator> loadKspCatalogTask =
                    Addressables.LoadContentCatalogAsync(ksp2CatalogFullPath, true);
                loadKspCatalogTask.WaitForCompletion();
            }

            // Load the Redux asset catalog too, if and only if this is the package version of KSP2 Unity Tools and there is no locator already registerd
            if (Assembly.GetExecutingAssembly().FullName == "ksp2community.ksp2unitytools.editor" && !Addressables
                .ResourceLocators
                .Select(rl => rl.LocatorId)
                .Where(id => id.Contains(reduxCatalogPath))
                .Any())
            {
                string reduxCatalogFullPath = Path.Join(Application.dataPath, reduxCatalogPath);
                AsyncOperationHandle<IResourceLocator> loadKspCatalogTask =
                    Addressables.LoadContentCatalogAsync(reduxCatalogFullPath, true);
                loadKspCatalogTask.WaitForCompletion();
            }
        }
#endif
    }
}