using KSP.Rendering.Planets;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.UIElements;

namespace Ksp2UnityTools.Editor.PlanetAuthoring.Biomes
{
    /// <summary>
    /// Read-only inspector for a baked <see cref="BiomeLookupHashTable" /> that renders the
    /// per-cell biome assignment as a color-coded preview image and a legend.
    /// </summary>
    /// <remarks>
    /// The runtime asset is bake output, so editing the 65,536-cell list by hand is never the
    /// right move. This inspector replaces the default IMGUI array view with a 1024x1024 preview
    /// rasterized from the packed chunks, a stats summary, and a KSP2BiomeType legend. To re-bake,
    /// the artist uses the Biome Lookup section on the PQS inspector.
    /// </remarks>
    [CustomEditor(typeof(BiomeLookupHashTable))]
    public class BiomeLookupHashTableEditor : UnityEditor.Editor
    {
        private const int PreviewResolution = 1024;

        // 17 entries matching KSP2BiomeType. Picked to be visually distinct rather than
        // physically realistic; this is a debug visualization, not a final color treatment.
        private static readonly Color[] BiomeColors =
        {
            new(0.10f, 0.10f, 0.10f, 1f), // NONE
            new(0.45f, 0.30f, 0.20f, 1f), // DIRT
            new(0.70f, 0.60f, 0.40f, 1f), // DUST
            new(0.20f, 0.65f, 0.20f, 1f), // GRASS
            new(0.55f, 0.55f, 0.25f, 1f), // GRASS_DRIED
            new(0.70f, 0.90f, 1.00f, 1f), // ICE
            new(0.20f, 0.40f, 0.30f, 1f), // MARSH
            new(0.70f, 0.70f, 0.75f, 1f), // METAL
            new(0.50f, 0.50f, 0.50f, 1f), // ROCK
            new(0.85f, 0.75f, 0.50f, 1f), // SAND
            new(0.95f, 0.95f, 1.00f, 1f), // SNOW
            new(0.30f, 0.50f, 0.80f, 1f), // WET
            new(0.75f, 0.75f, 0.70f, 1f), // CONCRETE
            new(0.05f, 0.15f, 0.40f, 1f), // OCEAN
            new(0.90f, 0.30f, 0.10f, 1f), // LAVA
            new(0.55f, 0.55f, 0.60f, 1f), // METAL_PLANET
            new(0.60f, 0.40f, 0.70f, 1f), // GAS_GIANT
        };

        private Texture2D _previewTexture;
        private string _previewContentHash;

        /// <inheritdoc />
        public override VisualElement CreateInspectorGUI()
        {
            var root = new VisualElement();
            var hashTable = target as BiomeLookupHashTable;
            if (hashTable == null)
            {
                root.Add(new Label("Target is not a BiomeLookupHashTable."));
                return root;
            }

            CountStats(hashTable, out var populatedCells, out var totalChunks);

            var statsLabel = new Label(
                $"Populated cells: {populatedCells:N0} / 65,536        Packed chunks: {totalChunks:N0}");
            statsLabel.style.marginTop = 4;
            statsLabel.style.marginBottom = 4;
            root.Add(statsLabel);

            // Cache the rendered texture keyed by a content hash so re-selecting the same asset
            // doesn't realloc 4MB. ReleasePreview still runs on OnDisable, so the texture lives
            // exactly as long as the inspector instance does.
            var contentHash = ComputeContentHash(hashTable);
            if (_previewTexture == null || _previewContentHash != contentHash)
            {
                ReleasePreview();
                _previewTexture = RenderPreview(hashTable);
                _previewContentHash = contentHash;
            }
            var image = new Image
            {
                image = _previewTexture,
                scaleMode = ScaleMode.ScaleToFit,
            };
            image.style.height = 512;
            image.style.marginBottom = 6;
            root.Add(image);

            root.Add(BuildLegend());

            root.Add(new HelpBox(
                "This asset is generated by the Bake button on the PQS inspector's Biome Lookup " +
                "section. Direct edits here will be overwritten on the next bake.",
                HelpBoxMessageType.Info));

            return root;
        }

        private void OnDisable()
        {
            ReleasePreview();
        }

        private void ReleasePreview()
        {
            if (_previewTexture != null)
            {
                DestroyImmediate(_previewTexture);
                _previewTexture = null;
            }
            _previewContentHash = null;
        }

        // Cheap content hash: combines cell count + total chunk count + first-and-last chunk values.
        // Sufficient to invalidate the cached preview on any meaningful bake-output change without
        // walking every chunk.
        private static string ComputeContentHash(BiomeLookupHashTable table)
        {
            if (table.Cells == null) return "null";
            var hash = new Hash128();
            hash.Append(table.Cells.Length);
            for (var i = 0; i < table.Cells.Length; i++)
            {
                var chunks = table.Cells[i].BiomeChunks;
                if (chunks == null || chunks.Count == 0) continue;
                hash.Append(i);
                hash.Append(chunks.Count);
                hash.Append(chunks[0]);
                hash.Append(chunks[chunks.Count - 1]);
            }
            return hash.ToString();
        }

        private static void CountStats(BiomeLookupHashTable table, out int populatedCells, out int totalChunks)
        {
            populatedCells = 0;
            totalChunks = 0;
            if (table.Cells == null) return;
            for (var i = 0; i < table.Cells.Length; i++)
            {
                var chunks = table.Cells[i].BiomeChunks;
                if (chunks == null || chunks.Count == 0) continue;
                populatedCells++;
                totalChunks += chunks.Count;
            }
        }

        // Rasterizes the hash table into a 1024x1024 RGBA32 preview. 256 outer cells per side,
        // each covering 4x4 preview pixels, with 16 sub-cells per cell side collapsing 4 sub-cells
        // into each preview pixel (sampled at the rounded center).
        private static Texture2D RenderPreview(BiomeLookupHashTable table)
        {
            var tex = new Texture2D(PreviewResolution, PreviewResolution, TextureFormat.RGBA32, false)
            {
                filterMode = FilterMode.Point,
                wrapMode = TextureWrapMode.Clamp,
                hideFlags = HideFlags.HideAndDontSave,
            };
            var pixels = new Color32[PreviewResolution * PreviewResolution];
            for (var i = 0; i < pixels.Length; i++)
            {
                pixels[i] = new Color32(20, 20, 20, 255);
            }

            if (table.Cells != null)
            {
                var outerDim = BiomeLookupHashTable.BiomeSamplingHashTableDimension; // 256
                var cellPx = PreviewResolution / outerDim;                           // 4 px per outer cell
                var innerDim = BiomeLookupHashTable.CellDimension;                   // 16 sub-cells per side
                // 4 / 16 = 0.25 px per sub-cell, so 4 sub-cells collapse to 1 preview pixel.
                // Pick the chunk that covers the sub-cell at the rounded center of each preview pixel.
                for (var cellY = 0; cellY < outerDim; cellY++)
                for (var cellX = 0; cellX < outerDim; cellX++)
                {
                    var chunks = table.Cells[cellX + cellY * outerDim].BiomeChunks;
                    if (chunks == null || chunks.Count == 0) continue;

                    var outerPx0 = cellX * cellPx;
                    var outerPy0 = cellY * cellPx;
                    for (var py = 0; py < cellPx; py++)
                    for (var px = 0; px < cellPx; px++)
                    {
                        var subX = (px * innerDim) / cellPx + (innerDim / cellPx) / 2;
                        var subY = (py * innerDim) / cellPx + (innerDim / cellPx) / 2;
                        var type = LookupTypeAt(chunks, subX, subY);
                        if (type < 0) continue;
                        var pxX = outerPx0 + px;
                        // Flip Y so the preview reads as a standard UV map (v=0 at the bottom).
                        var pxY = (PreviewResolution - 1) - (outerPy0 + py);
                        pixels[pxY * PreviewResolution + pxX] = TypeToColor32(type);
                    }
                }
            }

            tex.SetPixels32(pixels);
            tex.Apply(updateMipmaps: false, makeNoLongerReadable: true);
            return tex;
        }

        private static int LookupTypeAt(System.Collections.Generic.List<int> chunks, int subX, int subY)
        {
            for (var i = 0; i < chunks.Count; i++)
            {
                BiomeLookupHashTable.UnpackBiomeChunkData(chunks[i],
                    out var umin, out var umax, out var vmin, out var vmax, out var type, out _);
                if (subX >= umin && subX <= umax && subY >= vmin && subY <= vmax) return type;
            }
            return -1;
        }

        private static Color32 TypeToColor32(int type)
        {
            if (type < 0 || type >= BiomeColors.Length) return new Color32(255, 0, 255, 255);
            return BiomeColors[type];
        }

        private static VisualElement BuildLegend()
        {
            var legend = new VisualElement();
            legend.style.flexDirection = FlexDirection.Row;
            legend.style.flexWrap = Wrap.Wrap;
            legend.style.marginBottom = 4;

            var names = System.Enum.GetNames(typeof(PQSData.KSP2BiomeType));
            for (var i = 0; i < names.Length && i < BiomeColors.Length; i++)
            {
                var entry = new VisualElement();
                entry.style.flexDirection = FlexDirection.Row;
                entry.style.alignItems = Align.Center;
                entry.style.marginRight = 8;
                entry.style.marginBottom = 2;

                var swatch = new VisualElement();
                swatch.style.width = 12;
                swatch.style.height = 12;
                swatch.style.marginRight = 4;
                swatch.style.backgroundColor = BiomeColors[i];
                entry.Add(swatch);

                entry.Add(new Label(names[i]));
                legend.Add(entry);
            }
            return legend;
        }
    }
}
